### ISSUE TITLE
SE14 Kurse in .json Format übersetzen

### ISSUE THREAD

**Issue by DominikHorn** [FabianWildgrube/SE-StudyPlanner#1]
Bitte kurze Absprache mit @FabianWildgrube um Redundanzen zu vermeiden. Studienplan einsehbar unter https://elite-se.informatik.uni-augsburg.de/wp-content/uploads/2019/12/Studienempfehlungen-Deutsch-V8.pdf und im digicampus alle Veranstaltungen unter https://digicampus.uni-augsburg.de/plugins.php/mvvplugin/search/studiengaenge/studiengang/ae6b588525d6c29e90e7f3e7a656e940?sso=multiaccount&cancel_login=1&again=1

## Formale Methoden
* [x] Formale Methoden
* [x] Modellierung, Spezifikation und Verifikation
* [x] Modellbasierte Sicherheitsanalyse
* [x] Praktische IT-Sicherheit
* [x] Semantik von Programmiersprachen
* [x] Seminar Formale Methoden und IT-Sicherheit

## Datenbanken
* [x] Datenbanksysteme
* [x] Datenbanksysteme und moderne CPU-Architekturen
* [x] Web-Datenbanken
* [x] Grundlagen Data Engineering
* [x] Seminar Datenbanken

## Software Engineering & Verteilte Systeme
* [x] Software Engineering
* [x] Projektmanagement
* [x] Testen
* [x] Requirements Engineering
* [x] Modellbasierte Softwareentwicklung
* [x] Software Engineering für Embedded Systems
* [x] Software Engineering für Verteilte Systeme
* [x] Künstliche Intelligenz
* [x] Projektseminar Softwaretechnik
* [ ] Seminar Automotive Software Engineering / Seminar Grundlagen des Software und Systems Engineering / Seminar Softwaretechnik (es wird anscheinend nur eins angeboten)

## Softskillkurse
* [x] Erfolg im Team
* [x] Moderationstechniken
* [x] Präsentationstraining
* [ ] Projektseminar Soziales Engagement
* [x] Schreibtraining
* [x] Führungskompetenz
* [x] Change-Prozesse in verschiedenen Arbeitskontexten
* [x] Interkulturelle Kommunikation

## Human Computer Interaction
* [x] Human-Computer Interaction
* [x] Usability Engineering
* [x] Seminar Human-Computer-Interaction /  Seminar Maschinelles Lernen und innovative Interaktionstechniken (auch hier wahrscheinlich wieder nur eins)

## Sonstiges
* [x] Industriepraktikum
* [x] Masterarbeit

**Comment by Porrum** [comment]
Ich würde den HCI-Block übernehmen.
Was die Seminare angeht: Soweit ich weiß, werden aktiv gar keine angeboten, sondern wir müssen uns selber drum kümmern und bei den Profs anfragen, wenn wir ein "klassisches" Seminar machen wollen. Erwartet wird ja eigentlich, dass wir das PuLi machen.

**Comment by ricffb** [comment]
Dann trage ich schnell die Softskillkurse ein.

**Comment by ricffb** [comment]
mit #2  könnten wir die softskill dinger abhaken.

**Comment by Porrum** [comment]
und mit #3 den HCI-Block

**Comment by FabianWildgrube** [comment]
Super Sache, vielen Dank euch allen! ich schließe die Issue, da wir jetzt alle Veranstaltungen drin haben und wie @Porrum sagt, werden die meisten das PuLi machen bzw. mit den vorhandenen Seminaren, die wir modelliert haben "simulieren", wenn sie das PuLi nicht machen :)

**Comment by FabianWildgrube** [comment]
Der Vollständigkeit halber sind jetzt alle Seminare hinzugefügt.
